document:
  name: Linee Guida Open Data
  description: |
    Linee Guida recanti regole tecniche per l’attuazione del decreto legislativo 24 gennaio 2006, n. 36 e s.m.i. relativo all’apertura dei dati e al riutilizzo dell’informazione del settore pubblico.
  tags:
    - open data
    - linee guida
    - PSI
    - settore pubblico
    - dati
    - dati aperti
